name: "Build binaries & publish libs"

on:
  release:
    types: [published]

jobs:

  parse_tag:
    runs-on: ubuntu-latest
    env:
      # e.g. binary-name_v1.2.3-alpha -> binary-name & v1.2.3-alpha
      TAG_SPLIT: '^(.*)_(v[0-9]+\..*)$'
    outputs:
      binary: ${{ steps.is_binary.outputs.binary }}
      crate_name: ${{ steps.split_tag.outputs.crate_name }}
      version: ${{ steps.split_tag.outputs.version }}
    defaults:
      run:
        shell: bash
    steps:
      - name: split tag
        id: split_tag
        run: |
          if [[ ${{ github.event.release.tag_name }} =~ ${{ env.TAG_SPLIT }} ]]; then
            echo "crate_name=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "version=${BASH_REMATCH[2]}"  >> $GITHUB_OUTPUT
          fi
      - name: show outputs
        run: |
          echo "Crate: '${{ steps.split_tag.outputs.crate_name }}'"
          echo "Version: '${{ steps.split_tag.outputs.version }}'"
      - name: is binary?
        id: is_binary
        run: |   
          echo binary="${{ contains(fromJSON('["ninja-xtask"]'), steps.split_tag.outputs.crate_name) }}" >> $GITHUB_OUTPUT

  test:
    needs:
      - parse_tag
    strategy:
      fail-fast: true
      matrix:
        channel: ["stable", "beta", "nightly"]
    defaults:
      run:
        working-directory: ${{ needs.parse_tag.outputs.crate_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: update rust
      run: rustup set profile default && rustup install ${{ matrix.channel }}
    - name: Set bootstrap
      run: test "${{ matrix.channel }}" != "nightly"  && echo "RUSTC_BOOTSTRAP=1" >> $GITHUB_ENV || true
    - name: Run tests
      run: cargo "+${{ matrix.channel }}" test --no-fail-fast

  lint:
    needs:
      - parse_tag
    strategy:
      fail-fast: true
      matrix:
        channel: ["stable", "beta", "nightly"]
    defaults:
      run:
        working-directory: ${{ needs.parse_tag.outputs.crate_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: update rust
      run: rustup set profile default && rustup install ${{ matrix.channel }}
    - name: Set bootstrap
      run: test "${{ matrix.channel }}" != "nightly"  && echo "RUSTC_BOOTSTRAP=1" >> $GITHUB_ENV  || true
    - name: clippy
      run: cargo +${{ matrix.channel }} clippy -- --deny warnings

  publish_lib:
    needs:
      - parse_tag
      - test
      - lint
    environment: crates.io
    # permissions:
    #   id-token: write
    defaults:
      run:
        working-directory: ${{ needs.parse_tag.outputs.crate_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.release.target_commitish }}
    # Install manually as different crates my have custom toolchains defined
    - name: install rust
      run: rustup set profile default && rustup install
    # Use OIDC for updating existing crates
    - uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe #v1.0.4
      id: auth
    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      run:
        cargo publish
    # # # OR # # #
    # # Use API Token ONLY for creating a new crate
    # - name: Publish
    #   env:
    #     CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    #   run:
    #     cargo publish

  # Based upon action used by cargo-msrv.
  # Maybe the file type is incorrect for windows?
  build_binaries:
    needs: 
      - parse_tag
      - test
      - lint
    if: needs.parse_tag.outputs.binary == 'true'
    defaults:
      run:
        working-directory: ${{ needs.parse_tag.outputs.crate_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04 # Prevent building on the latest GLIBC. There's not really a need to, and Debian 12 users are still behind
            archive_ext: tgz
            kind: linux

          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04 # Prevent building on the latest GLIBC. There's not really a need to, and Debian 12 users are still behind
            archive_ext: tgz
            kind: linux

          - target: x86_64-apple-darwin
            os: macos-15-intel
            archive_ext: tgz
            kind: macos

          - target: aarch64-apple-darwin
            os: macos-latest
            archive_ext: tgz
            kind: macos

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            archive_ext: zip
            kind: windows

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout_tagged_commit
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: set_output
        id: set_output
        shell: bash
        run: |
          echo "archive=${{ needs.parse_tag.outputs.crate_name }}-${{ matrix.target }}-${{ needs.parse_tag.outputs.version }}.${{ matrix.archive_ext }}" >> $GITHUB_OUTPUT
          echo "subfolder=${{ needs.parse_tag.outputs.crate_name }}-${{ matrix.target }}-${{ needs.parse_tag.outputs.version }}" >> $GITHUB_OUTPUT

      - name: show_outputs
        shell: bash
        run: |
          echo "Archive: '${{ steps.set_output.outputs.archive }}'"
          echo "Subfolder: '${{ steps.set_output.outputs.subfolder }}'"

      - name: create_pkg_subfolder
        shell: bash
        run: mkdir ${{ steps.set_output.outputs.subfolder }}

      - name: copy_files_to_pkg_subfolder
        shell: bash
        run: |
          cp LICENSE ${{ steps.set_output.outputs.subfolder }}
          cp README.md ${{ steps.set_output.outputs.subfolder }}

      # Install manually as different crates my have custom toolchains defined
      - name: install rust
        run: rustup set profile default && rustup install

      - name: install musl-gcc
        if: matrix.target == 'x86_64-unknown-linux-musl'
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools # provides musl-gcc
          version: 1.0

      - name: build_${{ matrix.target }}_release_binary
        shell: bash
        run: cargo build --target=${{ matrix.target }} --release

      - name: install cargo about
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-about

      - name: generate_dep_licenses_file
        shell: bash
        run: cargo about generate --output-file "${{ steps.set_output.outputs.subfolder }}/third-party-licenses.html" about.hbs

      - name: pack_archive_macos
        if: matrix.kind == 'macos'
        shell: bash
        run: |
          cp  ./target/${{ matrix.target }}/release/${{ needs.parse_tag.outputs.crate_name }} ${{ steps.set_output.outputs.subfolder }}
          gtar --create --gzip --file=${{ steps.set_output.outputs.archive }} ${{ steps.set_output.outputs.subfolder }}

      - name: pack_archive_linux
        if: matrix.kind == 'linux'
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/${{ needs.parse_tag.outputs.crate_name }} ${{ steps.set_output.outputs.subfolder }}
          tar --create --gzip --file=${{ steps.set_output.outputs.archive }} ${{ steps.set_output.outputs.subfolder }}

      - name: pack_archive_windows
        if: matrix.kind == 'windows'
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/${{ needs.parse_tag.outputs.crate_name }}.exe ./${{ steps.set_output.outputs.subfolder }}
          7z a -tzip ${{ steps.set_output.outputs.archive }} ${{ steps.set_output.outputs.subfolder }}

      - name: upload_artifact
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.set_output.outputs.archive }}
          asset_name: ${{ steps.set_output.outputs.archive }}
          asset_content_type: application/gzip
