name: "Build binaries & publish libs"

on:
  release:
    types: [published]

jobs:

  parse_tag:
    runs-on: ubuntu-latest
    env:
      # e.g. binary-name_v1.2.3-alpha -> binary-name & v1.2.3-alpha
      TAG_SPLIT: '^(.*)_(v[0-9]+\..*)$'
    outputs:
      binary: ${{ steps.is_binary.outputs.binary }}
      crate_name: ${{ steps.split_tag.outputs.crate_name }}
      version: ${{ steps.split_tag.outputs.version }}
    defaults:
      run:
        shell: bash
    steps:
      - name: split tag
        id: split_tag
        run: |
          if [[ ${{ github.event.release.tag_name }} =~ ${{ env.TAG_SPLIT }} ]]; then
            echo "crate_name=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "version=${BASH_REMATCH[2]}"  >> $GITHUB_OUTPUT
          fi
      - name: show outputs
        run: |
          echo "Crate: '${{ steps.split_tag.outputs.crate_name }}'"
          echo "Version: '${{ steps.split_tag.outputs.version }}'"
      - name: is binary?
        id: is_binary
        run: |   
          echo binary="${{ contains(fromJSON('["ninja-xtask"]'), steps.split_tag.outputs.crate_name) }}" >> $GITHUB_OUTPUT

  test:
    needs:
      - parse_tag
    strategy:
      fail-fast: true
      matrix:
        channel: ["stable", "beta", "nightly"]
    defaults:
      run:
        working-directory: ${{ needs.parse_tag.outputs.crate_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: update rust
      run: rustup set profile default && rustup install ${{ matrix.channel }}
    - name: Set bootstrap
      run: test "${{ matrix.channel }}" != "nightly"  && echo "RUSTC_BOOTSTRAP=1" >> $GITHUB_ENV || true
    - name: Run tests
      run: cargo "+${{ matrix.channel }}" test --no-fail-fast

  lint:
    needs:
      - parse_tag
    strategy:
      fail-fast: true
      matrix:
        channel: ["stable", "beta", "nightly"]
    defaults:
      run:
        working-directory: ${{ needs.parse_tag.outputs.crate_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: update rust
      run: rustup set profile default && rustup install ${{ matrix.channel }}
    - name: Set bootstrap
      run: test "${{ matrix.channel }}" != "nightly"  && echo "RUSTC_BOOTSTRAP=1" >> $GITHUB_ENV  || true
    - name: clippy
      run: cargo +${{ matrix.channel }} clippy -- --deny warnings

  # Based upon action used by cargo-msrv.
  # Maybe the file type is incorrect for windows?
  build_binaries:
    needs: 
      - parse_tag
      - test
      - lint
    if: needs.parse_tag.outputs.binary == 'true'
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ${{ needs.parse_tag.outputs.crate_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: "x86_64-unknown-linux-gnu"
            glibc: "-g 2.35" # Ubuntu 24.04 still on glibc2.35, behind even debian oldstable
          - target: "x86_64-unknown-linux-musl"
          - target: "aarch64-apple-darwin"
    runs-on: ubuntu-latest
    steps:
      - name: checkout tagged commit
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: install toml-cli
        uses: taiki-e/install-action@v2
        with:
          tool: toml-cli

      # Flaky - requires EXACTLY ONE [[bin]] section
      - name: set binary name
        id: cargo_toml
        run: |
          echo "bin=$(toml get -r Cargo.toml bin[0].name)" >> $GITHUB_OUTPUT

      - name: set output paths
        id: set_output
        shell: bash
        run: |
          echo "archive=${{ needs.parse_tag.outputs.crate_name }}-${{ matrix.target }}-${{ needs.parse_tag.outputs.version }}.tgz" >> $GITHUB_OUTPUT
          echo "subfolder=${{ needs.parse_tag.outputs.crate_name }}-${{ matrix.target }}-${{ needs.parse_tag.outputs.version }}" >> $GITHUB_OUTPUT

      - name: show calculated paths
        shell: bash
        run: |
          echo "Archive: '${{ steps.set_output.outputs.archive }}'"
          echo "Subfolder: '${{ steps.set_output.outputs.subfolder }}'"
          echo "Binary: '${{ steps.cargo_toml.outputs.bin }}'"

      - name: create_pkg_subfolder
        shell: bash
        run: mkdir ${{ steps.set_output.outputs.subfolder }}

      # Install manually as different crates may have custom toolchains defined
      - name: install rust
        run: rustup set profile default && rustup install --target ${{ matrix.target }}

      - name: install zig for cross compilation
        uses: mlugg/setup-zig@v2

      - name: install build tooling
        uses: taiki-e/install-action@v2
        with:
          tool: "cargo-zigbuild,cargo-about"

      - name: install binstallable ninja 
        uses: taiki-e/install-action@v2
        with:
          tool: ninja-xtask@0.2.2

      - name: build ${{ matrix.target }} ${{ matrix.glibc }} --release
        run: cargo ninja build --target=${{ matrix.target }} ${{ matrix.glibc }} --release

      - name: generate licenses file
        run: cargo about generate --output-file third-party-licenses.html about.hbs

      - name: create archive
        run: |
          cp LICENSE ${{ steps.set_output.outputs.subfolder }}
          cp third-party-licenses.html ${{ steps.set_output.outputs.subfolder }}
          cp README.md ${{ steps.set_output.outputs.subfolder }}
          cp target/${{ matrix.target }}/release/${{ steps.cargo_toml.outputs.bin }} ${{ steps.set_output.outputs.subfolder }}
          tar --create --gzip --file=${{ steps.set_output.outputs.archive }} ${{ steps.set_output.outputs.subfolder }}

      - name: upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} '${{ steps.set_output.outputs.archive }}'

  publish_lib:
    needs:
      - parse_tag
      - test
      - lint
      - build_binaries
    if: ${{ !(failure() || cancelled()) }}
    environment: crates.io
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: ${{ needs.parse_tag.outputs.crate_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.release.target_commitish }}
    # Install manually as different crates may have custom toolchains defined
    - name: install rust
      run: rustup set profile default && rustup install
    # Use OIDC for updating existing crates
    - uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe #v1.0.4
      id: auth
    # - name: Publish
    #   env:
    #     CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
    #   run:
    #     cargo publish
    # # # OR # # #
    # Use API Token ONLY for creating a new crate
    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run:
        cargo publish
